import React, { useEffect, useState } from 'react'
import { Save, Plus, Trash2, ArrowLeft, Copy, Check, ChevronUp, ChevronDown, Code, Eye } from 'lucide-react'

interface VisualStep {
  type: 'navigate' | 'click' | 'type' | 'wait' | 'assert_text' | 'assert_visible' | 'screenshot'
  name: string
  selector?: string
  value?: string
  timeout?: number
}

interface TestBuilderProps {
  suiteId: number
  caseId?: number // If editing
  onNavigate: (tab: string, arg?: any) => void
}

export default function TestBuilder({ suiteId, caseId, onNavigate }: TestBuilderProps): React.JSX.Element {
  const [caseName, setCaseName] = useState('')
  const [caseDesc, setCaseDesc] = useState('')
  const [caseUrl, setCaseUrl] = useState('https://')
  const [steps, setSteps] = useState<VisualStep[]>([])
  
  const [copied, setCopied] = useState(false)
  const [activePane, setActivePane] = useState<'editor' | 'code'>('editor')

  // Load existing test case if editing
  useEffect(() => {
    async function loadCase(): Promise<void> {
      if (!caseId) return
      try {
        const testCase = await window.api.getCase(caseId)
        if (testCase) {
          setCaseName(testCase.name)
          setCaseDesc(testCase.description || '')
          setCaseUrl(testCase.url)
          setSteps(JSON.parse(testCase.steps))
        }
      } catch (err) {
        console.error('Failed to load test case:', err)
      }
    }
    loadCase()
  }, [caseId])

  // Real-time Playwright Code Generator
  const generatedCode = React.useMemo(() => {
    let code = `import { test, expect } from '@playwright/test';\n\n`
    code += `// Generated by Playwright Studio\n`
    code += `test('${caseName || 'Visual Test Scenario'}', async ({ page }) => {\n`
    code += `  // Set standard execution viewport\n`
    code += `  await page.setViewportSize({ width: 1280, height: 720 });\n\n`
    code += `  // Step 1: Navigate to Base URL\n`
    code += `  await page.goto('${caseUrl || 'https://'}', { waitUntil: 'load' });\n\n`

    steps.forEach((step, idx) => {
      const stepNum = idx + 2
      code += `  // Step ${stepNum}: ${step.name || step.type}\n`
      switch (step.type) {
        case 'navigate': {
          const url = step.value || caseUrl
          code += `  await page.goto('${url}', { waitUntil: 'load' });\n`
          break
        }
        case 'click':
          code += `  await page.click('${step.selector}');\n`
          break
        case 'type':
          code += `  await page.fill('${step.selector}', '${step.value || ''}');\n`
          break
        case 'wait':
          if (step.selector) {
            code += `  await page.waitForSelector('${step.selector}', { state: 'visible' });\n`
          } else if (step.value) {
            code += `  await page.waitForTimeout(${parseInt(step.value, 10) || 1000});\n`
          } else {
            code += `  await page.waitForTimeout(1000);\n`
          }
          break
        case 'assert_text':
          code += `  await page.waitForSelector('${step.selector}', { state: 'visible' });\n`
          code += `  await expect(page.locator('${step.selector}')).toContainText('${step.value || ''}');\n`
          break
        case 'assert_visible':
          code += `  await page.waitForSelector('${step.selector}', { state: 'visible' });\n`
          code += `  await expect(page.locator('${step.selector}')).toBeVisible();\n`
          break
        case 'screenshot':
          code += `  await page.screenshot({ path: '${step.value || 'step_' + idx + 1}_screenshot.png' });\n`
          break
      }
      code += `\n`
    })

    code += `});\n`
    return code
  }, [caseName, caseUrl, steps])

  // Handle Save
  async function handleSave(): Promise<void> {
    if (!caseName.trim()) {
      alert('Please enter a test case name')
      return
    }
    if (!caseUrl.trim() || caseUrl === 'https://') {
      alert('Please enter a valid target base URL')
      return
    }
    try {
      await window.api.saveCase(
        caseId || null,
        suiteId,
        caseName,
        caseDesc,
        caseUrl,
        JSON.stringify(steps)
      )
      onNavigate('suites')
    } catch (err) {
      console.error('Failed to save test case:', err)
    }
  }

  // Step operations
  function addStep(type: VisualStep['type']): void {
    const defaultNames: Record<VisualStep['type'], string> = {
      navigate: 'Navigate to URL',
      click: 'Click element',
      type: 'Enter text',
      wait: 'Wait for selector or timeout',
      assert_text: 'Verify element contains text',
      assert_visible: 'Verify element is visible',
      screenshot: 'Capture screenshot'
    }

    const newStep: VisualStep = {
      type,
      name: defaultNames[type],
      selector: type === 'navigate' || type === 'screenshot' ? undefined : '',
      value: type === 'navigate' ? caseUrl : '',
      timeout: type === 'wait' ? 5000 : undefined
    }

    setSteps([...steps, newStep])
  }

  function updateStep(index: number, updates: Partial<VisualStep>): void {
    const updated = [...steps]
    updated[index] = { ...updated[index], ...updates }
    setSteps(updated)
  }

  function deleteStep(index: number): void {
    const updated = [...steps]
    updated.splice(index, 1)
    setSteps(updated)
  }

  function moveStep(index: number, direction: 'up' | 'down'): void {
    if (direction === 'up' && index === 0) return
    if (direction === 'down' && index === steps.length - 1) return
    
    const targetIdx = direction === 'up' ? index - 1 : index + 1
    const updated = [...steps]
    const temp = updated[index]
    updated[index] = updated[targetIdx]
    updated[targetIdx] = temp
    setSteps(updated)
  }

  function handleCopyCode(): void {
    navigator.clipboard.writeText(generatedCode)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header controls */}
      <div className="flex flex-col md:flex-row md:items-center justify-between border-b border-slate-800 pb-4 gap-4">
        <div className="flex items-center space-x-3">
          <button
            onClick={() => onNavigate('suites')}
            className="p-2 rounded-lg bg-slate-850 hover:bg-slate-800 text-slate-400 hover:text-slate-200 transition"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <h1 className="text-2xl font-bold text-slate-100">
              {caseId ? 'Edit Test Case' : 'New Test Case Builder'}
            </h1>
            <p className="text-xs text-slate-400 mt-0.5">Define your browser automation flow step-by-step.</p>
          </div>
        </div>

        <div className="flex items-center space-x-2.5">
          {/* Toggle view on mobile */}
          <div className="flex bg-slate-900 border border-slate-800 rounded-lg p-1 md:hidden">
            <button
              onClick={() => setActivePane('editor')}
              className={`p-1.5 rounded text-xs font-semibold flex items-center space-x-1 ${
                activePane === 'editor' ? 'bg-indigo-600 text-white' : 'text-slate-400'
              }`}
            >
              <Eye className="w-3.5 h-3.5" />
              <span>Editor</span>
            </button>
            <button
              onClick={() => setActivePane('code')}
              className={`p-1.5 rounded text-xs font-semibold flex items-center space-x-1 ${
                activePane === 'code' ? 'bg-indigo-600 text-white' : 'text-slate-400'
              }`}
            >
              <Code className="w-3.5 h-3.5" />
              <span>Code</span>
            </button>
          </div>

          <button
            onClick={handleSave}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-semibold rounded-lg flex items-center space-x-2 transition active:scale-95 shadow-md shadow-indigo-600/15"
          >
            <Save className="w-4 h-4" />
            <span>Save Case</span>
          </button>
        </div>
      </div>

      {/* Main Grid Pane */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-8">
        {/* Left/Middle Pane: Editor */}
        <div
          className={`md:col-span-3 space-y-6 ${
            activePane === 'editor' ? 'block' : 'hidden md:block'
          }`}
        >
          {/* Metadata Block */}
          <div className="glass-panel p-5 space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-1">
                <label className="text-xs font-semibold text-slate-400">Test Case Name *</label>
                <input
                  type="text"
                  value={caseName}
                  onChange={(e) => setCaseName(e.target.value)}
                  placeholder="e.g. Verify Login Validation"
                  className="w-full px-3 py-2 text-sm glass-input"
                />
              </div>
              <div className="space-y-1">
                <label className="text-xs font-semibold text-slate-400">Base URL *</label>
                <input
                  type="text"
                  value={caseUrl}
                  onChange={(e) => setCaseUrl(e.target.value)}
                  placeholder="e.g. https://example.com/login"
                  className="w-full px-3 py-2 text-sm glass-input font-mono"
                />
              </div>
            </div>
            <div className="space-y-1">
              <label className="text-xs font-semibold text-slate-400">Description</label>
              <input
                type="text"
                value={caseDesc}
                onChange={(e) => setCaseDesc(e.target.value)}
                placeholder="Describe what scenarios this visual test script validates..."
                className="w-full px-3 py-2 text-sm glass-input"
              />
            </div>
          </div>

          {/* Test Steps Timeline Editor */}
          <div className="glass-panel p-5 space-y-4">
            <h2 className="text-base font-bold text-slate-200 border-b border-slate-800 pb-3">Test Sequence Flow</h2>
            
            <div className="space-y-4 max-h-[30rem] overflow-y-auto pr-1">
              {steps.length === 0 ? (
                <div className="text-center py-12 text-slate-500 text-sm flex flex-col items-center justify-center space-y-2">
                  <span>No custom steps added. The test runs a default navigation to the Base URL.</span>
                  <span className="text-xs text-slate-600">Click the action buttons below to construct your test suite steps.</span>
                </div>
              ) : (
                steps.map((step, idx) => (
                  <div
                    key={idx}
                    className="p-4 rounded-lg bg-slate-950/40 border border-slate-850 flex items-start justify-between gap-4 group"
                  >
                    <div className="flex-1 space-y-3">
                      {/* Step Header */}
                      <div className="flex items-center space-x-2">
                        <span className="w-5 h-5 flex items-center justify-center rounded-full bg-slate-800 text-[10px] text-slate-400 font-mono font-bold">
                          {idx + 1}
                        </span>
                        <input
                          type="text"
                          value={step.name}
                          onChange={(e) => updateStep(idx, { name: e.target.value })}
                          className="bg-transparent border-none text-sm font-semibold text-slate-200 focus:ring-0 w-64 p-0 outline-none hover:border-slate-800 border-b border-transparent focus:border-indigo-500"
                        />
                        <span className="text-[10px] px-2 py-0.5 rounded-full bg-indigo-500/10 text-indigo-400 font-mono font-semibold uppercase">
                          {step.type}
                        </span>
                      </div>

                      {/* Step Forms */}
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pl-7">
                        {step.type !== 'navigate' && step.type !== 'screenshot' && (
                          <div className="space-y-1">
                            <label className="text-[10px] font-semibold text-slate-500">Selector</label>
                            <input
                              type="text"
                              value={step.selector || ''}
                              onChange={(e) => updateStep(idx, { selector: e.target.value })}
                              placeholder="e.g. #username, .submit-btn, input[name='pwd']"
                              className="w-full px-2.5 py-1.5 text-xs glass-input font-mono"
                            />
                          </div>
                        )}
                        {(step.type === 'navigate' || step.type === 'type' || step.type === 'assert_text' || step.type === 'wait' || step.type === 'screenshot') && (
                          <div className="space-y-1">
                            <label className="text-[10px] font-semibold text-slate-500">
                              {step.type === 'navigate' ? 'Destination URL' : step.type === 'wait' ? 'Timeout (ms) or Value' : step.type === 'screenshot' ? 'Filename' : 'Value'}
                            </label>
                            <input
                              type="text"
                              value={step.value || ''}
                              onChange={(e) => updateStep(idx, { value: e.target.value })}
                              placeholder={step.type === 'navigate' ? 'Defaults to Base URL' : step.type === 'wait' ? 'e.g. 5000' : 'e.g. my-cool-text'}
                              className="w-full px-2.5 py-1.5 text-xs glass-input"
                            />
                          </div>
                        )}
                      </div>
                    </div>

                    {/* Step Reorder & Delete */}
                    <div className="flex items-center space-x-1.5 self-center">
                      <button
                        onClick={() => moveStep(idx, 'up')}
                        disabled={idx === 0}
                        className="p-1.5 rounded hover:bg-slate-800 text-slate-500 hover:text-slate-300 disabled:opacity-20 transition"
                      >
                        <ChevronUp className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => moveStep(idx, 'down')}
                        disabled={idx === steps.length - 1}
                        className="p-1.5 rounded hover:bg-slate-800 text-slate-500 hover:text-slate-300 disabled:opacity-20 transition"
                      >
                        <ChevronDown className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => deleteStep(idx)}
                        className="p-1.5 rounded hover:bg-red-500/10 text-slate-500 hover:text-red-400 transition"
                        title="Delete Step"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                ))
              )}
            </div>

            {/* Toolbox: Add Step Controls */}
            <div className="border-t border-slate-800 pt-4">
              <span className="text-xs font-semibold text-slate-400 block mb-3">Toolbox: Add Step Action</span>
              <div className="flex flex-wrap gap-2">
                {(['navigate', 'click', 'type', 'wait', 'assert_text', 'assert_visible', 'screenshot'] as const).map(
                  (type) => (
                    <button
                      key={type}
                      type="button"
                      onClick={() => addStep(type)}
                      className="px-3 py-1.5 text-xs bg-slate-900 border border-slate-800 hover:border-indigo-500/40 text-slate-300 hover:text-indigo-400 rounded-lg flex items-center space-x-1.5 transition active:scale-95"
                    >
                      <Plus className="w-3.5 h-3.5" />
                      <span className="capitalize">{type.replace('_', ' ')}</span>
                    </button>
                  )
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Right Pane: Generated Playwright Code (Sticky Panel) */}
        <div
          className={`md:col-span-2 glass-panel p-5 flex flex-col space-y-4 h-[calc(100vh-18rem)] md:sticky md:top-24 ${
            activePane === 'code' ? 'block' : 'hidden md:flex'
          }`}
        >
          <div className="flex items-center justify-between border-b border-slate-800 pb-3 flex-shrink-0">
            <div className="flex items-center space-x-2 text-slate-200">
              <Code className="w-5 h-5 text-indigo-400" />
              <h2 className="font-bold text-sm">Playwright spec.ts (Dynamic Preview)</h2>
            </div>
            
            <button
              onClick={handleCopyCode}
              className="p-1.5 rounded bg-slate-850 hover:bg-slate-800 text-slate-400 hover:text-slate-200 flex items-center space-x-1 text-xs font-semibold border border-slate-800/80 transition"
              title="Copy to Clipboard"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  <span className="text-emerald-400">Copied</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy</span>
                </>
              )}
            </button>
          </div>

          {/* Generated Code Window */}
          <div className="flex-1 bg-slate-950/80 border border-slate-900 rounded-lg p-4 overflow-auto font-mono text-xs text-indigo-300 leading-relaxed scrollbar-thin">
            <pre className="whitespace-pre">{generatedCode}</pre>
          </div>
        </div>
      </div>
    </div>
  )
}
